Testing threading for comments
MattNotarangelo/PR-review-google-chat-action pull request #25
Opened 2023-11-02 08:44 UTC by amogh-rokt

2023-11-02 08:47 UTC, amogh-rokt commented
testing

2023-11-02 08:48 UTC, moq4 reviewed
ok

2023-11-02 08:49 UTC, moq4 commented
test

2023-11-02 08:51 UTC, moq4 reviewed
sdf

2023-11-02 08:54 UTC, moq4 reviewed
asd

2023-11-02 08:56 UTC, moq4 reviewed
review

2023-11-02 08:59 UTC, moq4 reviewed
sdf

2023-11-02 09:05 UTC, moq4 reviewed
pls

2023-11-02 09:06 UTC, moq4 reviewed
ok

2023-11-02 09:20 UTC, moq4 commented on index.js
> +  console.log(github);
good

2023-11-02 09:24 UTC, moq4 commented on index.js
> +
ya

2023-11-02 09:25 UTC, moq4 requested changes
wtf

2023-11-02 09:29 UTC, moq4 approved these changes
lgtm

2023-11-02 09:32 UTC, moq4 approved these changes
lgtm

2023-11-02 09:32 UTC, moq4 reviewed
sdfsdf

2023-11-02 09:32 UTC, moq4 requested changes
wtf

2023-11-02 09:42 UTC, moq4 reviewed
sdf

2023-11-02 09:43 UTC, moq4 requested changes
wtf

2023-11-02 09:43 UTC, moq4 approved these changes
lgtm!

2023-11-02 09:44 UTC, merged

2023-11-14 09:07 UTC, jacobsalway commented
nice